config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :abstractor_abstraction_groups do
    member do
      put :update_wokflow_status
    end
  end

  resources :abstractor_abstractions do
    collection do
      put :update_all
      put :discard
      put :undiscard
      put :update_wokflow_status
    end
    member do
      put :clear
    end
    resources :abstractor_suggestions
  end

  resources :abstractor_abstraction_schemas, only: [:index, :show] do
    resources :abstractor_object_values
  end

  resources :abstractor_rules do
  end

  resources :abstractor_object_value_variants
  resources :notes do
    collection { get :next_note }
    collection { get :previous_note }
  end

  resources :note_stable_identifiers do
    member do
      post :abstractor_suggestions
    end
  end

  resources :providers, only: :index
  resources :provider_specialties, only: :index
  resources :users, only: :show

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/abstractor/abstractor_object_value.rb
module Abstractor
  class AbstractorObjectValue < ActiveRecord::Base
    include Abstractor::Methods::Models::AbstractorObjectValue
    # @!parse extend Moo::ClassMethods
  end
end

app/controllers/abstractor_object_values_controller.rb
class AbstractorObjectValuesController < ApplicationController
  include Abstractor::Methods::Controllers::AbstractorObjectValuesController
end

app/views/abstractor_object_values/_abstractor_object_value_variant_fields.html.haml
%tr{ class: 'abstractor-object-value-variant', data: { new_record: "#{form.object.new_record?}" } }
  %td.value
    = form.hidden_field :id
    = form.hidden_field :_destroy
    .input-field
      = form.text_field :value, class: 'autocomplete', autocomplete: 'off', disabled: form.object.used?
    - if validation_errors?(form.object, :value)
      %p.error= format_validation_errors(form.object, :value)
  %td.case_sensitive
    %label
      = form.check_box :case_sensitive, disabled: form.object.used?
      %span
        Case Sensitive?
  %td.remove.right-align
    = link_to 'Remove', '#', class: 'btn wave-effect waves-light red', data: { action: 'click->abstractor-object-value-variants#remove_association' }

app/views/abstractor_object_values/_form.html.haml
= form_for @abstractor_object_value, url: @path, local: false, id: 'abstractor-object-value-form', data: { controller: 'abstractor-object-values' } do |f|
  .abstractor_object_value_value.input-field.col.s12
    = f.text_field :value, disabled: @abstractor_object_value.used?
    = label_tag :value, "Value *", for: 'abstractor_abstractor_object_value_value'
    - if validation_errors?(@abstractor_object_value, :value)
      %p.error= format_validation_errors(@abstractor_object_value, :value)
  .abstractor_object_value_vocabulary_code.input-field.col.s12
    = f.text_field :vocabulary_code, disabled: @abstractor_object_value.used?
    = label_tag :vocabulary_code, 'Vocabulary Code *', for: 'abstractor_abstractor_object_value_vocabulary_code'
    - if validation_errors?(@abstractor_object_value, :vocabulary_code)
      %p.error= format_validation_errors(@abstractor_object_value, :vocabulary_code)
  .abstractor_object_value_case_sensitive.col.s12
    %label
      = f.check_box :case_sensitive, disabled:  @abstractor_object_value.used?
      %span
        Case Sensitive?
  .abstractor_object_value_comments.input-field.col.s12
    = f.text_area :comments, class: 'materialize-textarea'
    = label_tag :comments, nil, for: 'abstractor_abstractor_object_value_comments'
  .abstractor_object_value_variants
    %h3
      Variant Values
    %div{ data: { controller: 'abstractor-object-value-variants' } }
      %template{ data: { target: 'abstractor-object-value-variants.template' } }
        = f.fields_for :abstractor_object_value_variants, Abstractor::AbstractorObjectValueVariant.new, child_index: 'NEW_RECORD' do |abstractor_object_value_variant|
          = render 'abstractor_object_value_variant_fields', form: abstractor_object_value_variant
      %table.s12
        %thead
          %tr
            %th.variant_value{ width: 200 }
              Variant Value
              %span{ class: 'required' }
            %th.case_sensitive{ width: 200 }
              Case Sensitive?
            %th.remove.right-align{ width: 100 }
        %tbody.abstractor_object_value_variants_list{ data: { target: 'abstractor-object-value-variants.list' }}
          = f.fields_for :abstractor_object_value_variants, @abstractor_object_value.abstractor_object_value_variants.order(value: :asc) do |abstractor_object_value_variant|
            = render 'abstractor_object_value_variant_fields', form: abstractor_object_value_variant
      %div
        = link_to 'Add Variant Value', '#', id: 'add-abstractor-object-value-variant', class: 'btn wave-effect waves-light', data: { action: 'click->abstractor-object-value-variants#add_association'  }
  .row
    .navigation.col.offset-l9.l3
      %p.help-text
        %span{ class: 'required' }
        Indicates required field
      = f.submit 'Save', class: 'btn wave-effect waves-light'
      = link_to 'Cancel', Abstractor::UserInterface.abstractor_relative_path(abstractor_abstraction_schema_abstractor_object_values_path(@abstractor_abstraction_schema)), class: 'abstractor_abstraction_schema_values_index_link'

app/views/abstractor_object_values/edit.html.haml
#abstractor_object_value.row
  %h2.col.s12
    Edit Value
  #abstractor_object_value_form.row.s12
    = render 'form'

app/views/abstractor_object_values/index.html.haml
- content_for(:title) do
  Object Values
.row
  #abstractor_object_values.col.s12
    .abstractor_object_values_header
      %h1
        = @abstractor_abstraction_schema.display_name
        Values
      .row
        = link_to 'Schemas', abstractor_abstraction_schemas_url, class: 'waves-effect'
      .row
        = form_tag abstractor_abstraction_schema_abstractor_object_values_url(), method: :get, id: 'search_abstractor_object_values_form' do
          .row
            .search.input-field.col.s12
              = label_tag :search, 'Search'
              = text_field_tag :search, (params[:search].nil? ? '' : params[:search]), type: 'search'
          .row
            .navigation.col.l4.push-l8.s6.push-s6.right-align
              %button{ :type => 'submit', :id => 'search_abstractor_object_values_button', class: 'waves-effect waves-light btn' }
                Search
              = link_to 'Clear', abstractor_abstraction_schema_abstractor_object_values_url()
    .abstractor_object_values_list.col.s12.right-align
      .row
        = will_paginate @abstractor_object_values, renderer: MaterializePagination::Rails
        %table
          %thead
            %tr
              %th.abstractor_object_value_value{ width: 200 }
                = sortable 'value'
              %th.abstractor_object_value_vocabulary_code{ width: 100 }
                = sortable 'vocabulary_code'
              %th.abstractor_object_value_edit{ width: 300 }
              %th.abstractor_object_value_delete{ width: 300 }
          %tbody
            - @abstractor_object_values.each_with_index do |abstractor_object_value, i|
              = content_tag_for(:tr, abstractor_object_value ) do
                %td.abstractor_object_value_value
                  = abstractor_object_value.value
                %td.abstractor_object_value_vocabulary_code
                  = abstractor_object_value.vocabulary_code
                %td.abstractor_object_value_edit.right-align
                  = link_to 'Edit', Abstractor::UserInterface.abstractor_relative_path(edit_abstractor_abstraction_schema_abstractor_object_value_path(@abstractor_abstraction_schema, abstractor_object_value)), class: 'edit_abstraction_schema_abstractor_object_value_link waves-effect waves-light btn'
                %td.abstractor_object_value_delete.right-align
                  = link_to 'Delete', Abstractor::UserInterface.abstractor_relative_path(abstractor_abstraction_schema_abstractor_object_value_path(@abstractor_abstraction_schema, abstractor_object_value)), method: :delete, class: 'delete_abstractor_abstraction_schema_abstractor_object_value_link waves-effect waves-light btn red', data: { confirm: 'Are you sure?' }
        = will_paginate @abstractor_object_values, renderer: MaterializePagination::Rails
    .row
      .col.s12.left-align
        = link_to 'New', Abstractor::UserInterface.abstractor_relative_path(new_abstractor_abstraction_schema_abstractor_object_value_path(@abstractor_abstraction_schema)), class: 'new_abstractor_abstraction_schema_abstractor_object_value_link waves-effect waves-light btn'

app/views/abstractor_object_values/new.html.haml
#abstractor_object_value.row
  %h2.col.s12
    New Value
  #abstractor_object_value_form.row.s12
    = render 'form'