config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :abstractor_abstraction_groups do
    member do
      put :update_wokflow_status
    end
  end

  resources :abstractor_abstractions do
    collection do
      put :update_all
      put :discard
      put :undiscard
      put :update_wokflow_status
    end
    member do
      put :clear
    end
    resources :abstractor_suggestions
  end

  resources :abstractor_abstraction_schemas, only: [:index, :show] do
    resources :abstractor_object_values
  end

  resources :abstractor_rules do
  end

  resources :abstractor_object_value_variants
  resources :notes do
    collection { get :next_note }
    collection { get :previous_note }
  end

  resources :note_stable_identifiers do
    member do
      post :abstractor_suggestions
    end
  end

  resources :providers, only: :index
  resources :provider_specialties, only: :index
  resources :users, only: :show

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/note.rb
class Note < ApplicationRecord
  self.table_name = 'note'
  self.primary_key = 'note_id'
  belongs_to :note_type, class_name: 'Concept', foreign_key: 'note_type_concept_id'
  belongs_to :note_class, class_name: 'Concept', foreign_key: 'note_class_concept_id'
  belongs_to :person, class_name: 'Person', foreign_key: 'person_id', optional: true
  belongs_to :provider, class_name: 'Provider', foreign_key: 'provider_id', optional: true

  ABSTRACTOR_SITE_STATUS_ACCEPTED_SITE = 'accepted'
  ABSTRACTOR_SITE_STATUS_ACCEPTED_SPECIFIC_SITE = 'accepted specific'
  ABSTRACTOR_SITE_STATUS_ACCEPTED_GENERAL_SITE = 'accepted general'
  ABSTRACTOR_SITE_STATUS_SUGGESTED_SITE = 'suggested'
  ABSTRACTOR_SITE_STATUS_SUGGESTED_SPECIFIC_SITE = 'suggested specific'
  ABSTRACTOR_SITE_STATUS_SUGGESTED_GENERAL_SITE = 'suggested general'
  ABSTRACTOR_SITE_STATUS_NOT_APPLICABLE = 'not applicable'
  ABSTRACTOR_SITE_STATUS_NOT_APPLICABLE_SUGGESTED = 'not applicable suggested'
  ABSTRACTOR_SITE_STATUS_UNKNOWN_SUGGESTED = 'unknown suggested'

  ABSTRACTOR_HISTOLOGY_STATUS_ACCEPTED_HISTOLOGY = 'accepted'
  ABSTRACTOR_HISTOLOGY_STATUS_ACCEPTED_SPECIFIC_HISTOLOGY = 'accepted specific'
  ABSTRACTOR_HISTOLOGY_STATUS_ACCEPTED_GENERAL_HISTOLOGY = 'accepted general'
  ABSTRACTOR_HISTOLOGY_STATUS_SUGGESTED_HISTOLOGY = 'suggested'
  ABSTRACTOR_HISTOLOGY_STATUS_SUGGESTED_SPECIFIC_HISTOLOGY = 'suggested specific'
  ABSTRACTOR_HISTOLOGY_STATUS_SUGGESTED_GENERAL_HISTOLOGY = 'suggested general'
  ABSTRACTOR_HISTOLOGY_STATUS_NOT_APPLICABLE = 'not applicable'
  ABSTRACTOR_HISTOLOGY_STATUS_NOT_APPLICABLE_SUGGESTED = 'not applicable suggested'
  ABSTRACTOR_HISTOLOGY_STATUS_UNKNOWN_SUGGESTED = 'unknown suggested'
  ABSTRACTOR_SITE_STATUSES = [ABSTRACTOR_SITE_STATUS_ACCEPTED_SITE, ABSTRACTOR_SITE_STATUS_ACCEPTED_SPECIFIC_SITE, ABSTRACTOR_SITE_STATUS_ACCEPTED_GENERAL_SITE, ABSTRACTOR_SITE_STATUS_SUGGESTED_SITE, ABSTRACTOR_SITE_STATUS_SUGGESTED_SPECIFIC_SITE, ABSTRACTOR_SITE_STATUS_SUGGESTED_GENERAL_SITE, ABSTRACTOR_SITE_STATUS_NOT_APPLICABLE, ABSTRACTOR_SITE_STATUS_NOT_APPLICABLE_SUGGESTED, ABSTRACTOR_SITE_STATUS_UNKNOWN_SUGGESTED]
  ABSTRACTOR_HISTOLOGY_STATUSES = [ABSTRACTOR_HISTOLOGY_STATUS_ACCEPTED_HISTOLOGY, ABSTRACTOR_HISTOLOGY_STATUS_ACCEPTED_SPECIFIC_HISTOLOGY, ABSTRACTOR_HISTOLOGY_STATUS_ACCEPTED_GENERAL_HISTOLOGY, ABSTRACTOR_HISTOLOGY_STATUS_SUGGESTED_HISTOLOGY, ABSTRACTOR_HISTOLOGY_STATUS_SUGGESTED_SPECIFIC_HISTOLOGY, ABSTRACTOR_HISTOLOGY_STATUS_SUGGESTED_GENERAL_HISTOLOGY, ABSTRACTOR_HISTOLOGY_STATUS_NOT_APPLICABLE, ABSTRACTOR_HISTOLOGY_STATUS_NOT_APPLICABLE_SUGGESTED, ABSTRACTOR_HISTOLOGY_STATUS_UNKNOWN_SUGGESTED]

  def other_notes(options ={})
    abstractor_abstraction_status = options[:abstractor_abstraction_status] || nil
    namespace_ids = options[:namespace_id].blank? ? Abstractor::AbstractorNamespace.all.map(&:id) : [options[:namespace_id]]
    if namespace_ids.present?
      namespace_type = Abstractor::AbstractorNamespace.to_s
    end
    NoteStableIdentifier.search_across_fields(nil, nil, nil, nil, nil, {}).where('note.person_id = ? AND note.note_id != ?', self.person_id, self.note_id).by_abstractor_abstraction_status(abstractor_abstraction_status, namespace_type: namespace_type, namespace_id: namespace_ids)
  end

  def procedure_occurences(options={})
    options.reverse_merge!({ include_parent_procedures: true })
    get_procedures(options)
  end

  def note_stable_identifier
    if NoteStableIdentifierFull.where(note_id: self.note_id).first
      NoteStableIdentifierFull.where(note_id: self.note_id).first.note_stable_identifier
    end
  end

  private

    def get_procedures(options)
      domain_concept_procedure = Concept.domain_concepts.where(concept_name: 'Procedure').first
      domain_concept_note = Concept.domain_concepts.where(concept_name: 'Note').first
      relationship_has_proc_context = Relationship.where(relationship_id: 'Has proc context').first
      procedure_occurence_ids = FactRelationship.where(domain_concept_id_1: domain_concept_note.concept_id, fact_id_1: self.note_id, domain_concept_id_2: domain_concept_procedure.concept_id, relationship_concept_id: relationship_has_proc_context.relationship_concept_id).map(&:fact_id_2)
      procedures = SqlAudit.find_and_audit(options[:username], ProcedureOccurrence.where(procedure_occurrence_id: procedure_occurence_ids))
      procedures = procedures.to_a
      if options[:include_parent_procedures]
        procedures_temp = procedures.dup
        procedures_temp.each do |procedure|
          procedures.concat(procedure.procedure_occurences(username: options[:username]))
        end
      end
      procedures.uniq!
      procedures
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  before_action :load_note, only: [:edit]
  helper_method :sort_column, :sort_direction

  def index
    if params[:provider_speciality].present?
      @provider_specialties = Concept.provider_specialties.where(concept_id: params[:provider_speciality])
    else
      @provider_specialties = []
    end

    if params[:secondary_provider_speciality].present?
      @secondary_provider_specialties = Concept.provider_specialties.where(concept_id: params[:secondary_provider_speciality])
    else
      @secondary_provider_specialties = []
    end

    if params[:provider].present?
      @providers = Provider.where(provider_name: params[:provider])
    else
      @providers = []
    end

    if params[:secondary_provider].present?
      @secondary_providers = Provider.where(provider_name: params[:secondary_provider])
    else
      @secondary_providers = []
    end

    session[:index_history] = request.url unless params[:next_note]
    params[:page]||= 1
    options = {}
    options[:sort_column] = sort_column
    options[:sort_direction] = sort_direction
    @abstractor_namespaces = Abstractor::AbstractorNamespace.where(subject_type: NoteStableIdentifier.to_s).order('name ASC')
    @namespace_type = Abstractor::AbstractorNamespace.to_s
    @namespace_id = params[:namespace_id].blank? ? 0 : params[:namespace_id]
    @abstractor_abstraction_status = params[:abstraction_status] || Abstractor::Enum::ABSTRACTION_STATUS_NEEDS_REVIEW
    @abstractor_site_status = params[:abstraction_site_status] || 'all'
    @abstractor_histology_status = params[:abstraction_histology_status] || 'all'
    @abstractor_site = params[:abstraction_site] || []
    @abstractor_histology = params[:abstraction_histology] || []

    abstractor_abstraction_schema_id_has_cancer_site = Abstractor::AbstractorSubject.joins(:abstractor_abstraction_schema).where("abstractor_abstraction_schemas.predicate = 'has_cancer_site' AND abstractor_subjects.namespace_type = ? AND abstractor_subjects.namespace_id = ?", @namespace_type, @namespace_id).select('DISTINCT abstractor_subjects.abstractor_abstraction_schema_id').map(&:abstractor_abstraction_schema_id).first
    @sites = Abstractor::AbstractorSubject.joins(:abstractor_abstraction_schema => { :abstractor_abstraction_schema_object_values => :abstractor_object_value }).where("abstractor_abstraction_schemas.predicate = 'has_cancer_site'").select('DISTINCT abstractor_object_values.value').order(:value)

    abstractor_abstraction_schema_id_has_cancer_histology = Abstractor::AbstractorSubject.joins(:abstractor_abstraction_schema).where("abstractor_abstraction_schemas.predicate = 'has_cancer_histology' AND abstractor_subjects.namespace_type = ? AND abstractor_subjects.namespace_id = ?", @namespace_type, @namespace_id).select('DISTINCT abstractor_subjects.abstractor_abstraction_schema_id').map(&:abstractor_abstraction_schema_id).first
    @histologies = Abstractor::AbstractorSubject.joins(:abstractor_abstraction_schema => { :abstractor_abstraction_schema_object_values => :abstractor_object_value }).where("abstractor_abstraction_schemas.predicate = 'has_cancer_histology'").select('DISTINCT abstractor_object_values.value').order(:value).to_a

    abstractor_abstraction_schema_id_has_metastatic_cancer_histology = Abstractor::AbstractorSubject.joins(:abstractor_abstraction_schema).where("abstractor_abstraction_schemas.predicate = 'has_metastatic_cancer_histology'").select('DISTINCT abstractor_subjects.abstractor_abstraction_schema_id').map(&:abstractor_abstraction_schema_id).first
    @histologies.concat(Abstractor::AbstractorSubject.joins(:abstractor_abstraction_schema => { :abstractor_abstraction_schema_object_values => :abstractor_object_value }).where("abstractor_abstraction_schemas.predicate = 'has_metastatic_cancer_histology'").select('DISTINCT abstractor_object_values.value').order(:value).to_a)

    @note_stable_identifiers = SqlAudit.find_and_audit(
      current_user.username,
      NoteStableIdentifier.search_across_fields(params[:search], params[:provider], params[:secondary_provider], params[:provider_speciality], params[:secondary_provider_speciality], options).by_abstractor_abstraction_status(@abstractor_abstraction_status, namespace_type: @namespace_type, namespace_id: @namespace_id).by_note_date(params[:date_from], params[:date_to]).having_site(namespace_type: @namespace_type, namespace_id: @namespace_id, abstractor_site_status: @abstractor_site_status, abstractor_site: @abstractor_site).having_histology(namespace_type: @namespace_type, namespace_id: @namespace_id, abstractor_histology_status: @abstractor_histology_status, abstractor_histology: @abstractor_histology)
    )

    if params[:next_note]
      index = params[:index].to_i
      notes = @note_stable_identifiers.map(&:note_id)
      record_history
      if notes.any?
        if notes.size > (index + 1)
          if notes[index] == params[:previous_note_id].to_i
            index = index + 1
          end
          next_case = notes[index]
        else
          index = 0
          next_case = notes[0]
        end

        redirect_to edit_note_url(next_case, index: index, namespace_type: @namespace_type, namespace_id: @namespace_id) and return
      else
        redirect_to notes_path and return
      end
    end

    respond_to do |format|
      format.html { @note_stable_identifiers = NoteStableIdentifier.search_across_fields(params[:search], params[:provider], params[:secondary_provider], params[:provider_speciality], params[:secondary_provider_speciality], options).by_abstractor_abstraction_status(@abstractor_abstraction_status, namespace_type: @namespace_type, namespace_id: @namespace_id).by_note_date(params[:date_from], params[:date_to]).having_site(namespace_type: @namespace_type, namespace_id: @namespace_id, abstractor_site_status: @abstractor_site_status, abstractor_site: @abstractor_site).having_histology(namespace_type: @namespace_type, namespace_id: @namespace_id, abstractor_histology_status: @abstractor_histology_status, abstractor_histology: @abstractor_histology).paginate(per_page: 10, page: params[:page]); record_history }
    end
  end

  def edit
    @namespace_type = Abstractor::AbstractorNamespace.to_s
    @namespace_id = params[:namespace_id].blank? ? 0 : params[:namespace_id]

    unless params[:previous_case]
      session[:previous_note] ||= []
      if session[:current_note]
        session[:previous_note] << session[:current_note]
      end
      session[:current_note] = params[:id]
    end

    respond_to do |format|
      format.html
    end
  end

  def next_note
    @namespace_type = Abstractor::AbstractorNamespace.to_s
    @namespace_id = params[:namespace_id].blank? ? 0 : params[:namespace_id]

    if session[:history]
      session[:history].gsub!("&next_case=true","")
      session[:history].gsub!(/&index=(\d*)/,"")
      session[:history].gsub!(/&previous_note_id=(\d*)/,"")
      session[:history].gsub!(/notes\?(\d*)/,"/notes\?")
      session[:history] = session[:history] + (session[:history].include?('?') ? "&next_note=true&index=#{params[:index]}&previous_note_id=#{params[:previous_note_id]}" : "?&next_case=true&index=#{params[:index]}&previous_pathology_case_id=#{params[:previous_note_id]}&namespace_type=#{@namespace_type}&namespace_id=#{@namespace_id}")
      redirect_to session[:history] and return
    else
      redirect_to notes_url and return
    end
  end

  def previous_note
    @namespace_type = Abstractor::AbstractorNamespace.to_s
    @namespace_id = params[:namespace_id].blank? ? 0 : params[:namespace_id]
    if session[:previous_note].any?
      redirect_to edit_note_url(session[:previous_note].pop, previous_note: true, namespace_type: @namespace_type, namespace_id: @namespace_id) and return
    else
      redirect_to notes_url and return
    end
  end

  private
    def load_note
      @note = SqlAudit.find_and_audit(current_user.username, Note.where(note_id: params[:id])).first
      @person = SqlAudit.find_and_audit(current_user.username, Person.where(person_id: @note.person_id)).first
      @mrns = SqlAudit.find_and_audit(current_user.username, @person.mrns)
      @provider = SqlAudit.find_and_audit(current_user.username, Provider.where(provider_id: @note.provider_id)).first
    end

    def sort_column
      ['note_date', 'note_type', 'note_title', 'first_name', 'last_name'].include?(params[:sort]) ? params[:sort] : 'note_date'
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
    end
end

app/views/notes/_note.html.haml
%h1
  Note
.row
  .note_date.col.s12.l2
    %b
      Note Date
    %br
    = note.note_date.to_s(:date)
  .note_type.col.s12.l2
    %b
      Note Type
    %br
    = note.note_type.concept_name
  .note_class.col.s12.l2
    %b
      Note Class
    %br
    = note.note_class.concept_name
  .note_title.col.s12.l3
    %b
      Title
    %br
    = note.note_title
  .provider.col.s12.l3
    %b
      Provider
    %br
    = note.provider.provider_name if note.provider.present?
.row
  .note_text.col.s12.l12
    %b
      Note Text
    %br
    = format_text(ERB::Util.html_escape(note.note_text))

app/views/notes/edit.html.haml
#note.row
  .row
    %h1.col.l12
      Note
  .row
    .navigation.col.l12
      = link_to 'Back', controller.back_from_note_edit, class: 'back-note-link'
      |
      = link_to 'Notes', notes_path, class: 'notes-link'
      |
      = link_to 'Previous', previous_note_notes_path(namespace_type: @namespace_type, namespace_id: @namespace_id), class: 'previous-note-link'
      |
      = link_to 'Next', next_note_notes_path(index: params[:index], previous_note_id: @note.note_id, namespace_type: @namespace_type, namespace_id: @namespace_id), class: 'next-note-link'
  .row
    .patient.col.s12.l2
      %b
        Patient
      %br
      = @person.full_name
    .mrns.col.s12.l2
      %b
        MRN(s):
      - @mrns.each do |mrn|
        .mrn
          %b
            = mrn.health_system
          = mrn.mrn
    .note_date.col.s12.l2
      %b
        Note Date
      %br
      = @note.note_date.to_s(:date)
    .note_type.col.s12.l1
      %b
        Note Type
      %br
      = @note.note_type.concept_name
    .note_class.col.s12.l1
      %b
        Note Class
      %br
      = @note.note_class.concept_name
    .note_title.col.s12.l2
      %b
        Title
      %br
      = @note.note_title
    .provider.col.s12.l2
      %b
        Provider
      %br
      = @provider.provider_name if @provider.present?
  #procedure_occurrences.row
    .row
      %h4.col.l12
        Procedures
    .row
      .procedure_concept.col.s12.l2
        %b
          Procedure
      .procedure_date.col.s12.l2
        %b
          Date
      .provider.col.s12.l2
        %b
          Provider
      .specimens.col.s12.l3
        %b
          Specimens
      .notes.col.s12.l3.center-align
        %b
          Notes
    - procedure_occurences = @note.procedure_occurences(username: current_user.username)
    - if procedure_occurences.any?
      - procedure_occurences.each do |procedure_occurence|
        .row.procedure_occurrence
          .procedure_concept.col.s12.l2
            - if procedure_occurence.procedure_concept
              = procedure_occurence.procedure_concept.concept_name
          .procedure_date.col.s12.l2
            = procedure_occurence.procedure_date.to_s(:date)
          .provider.col.s12.l2
            = procedure_occurence.provider.provider_name if procedure_occurence.provider.present?
          .specimens.col.s12.l3
            - specimens = procedure_occurence.specimens(username: current_user.username)
            - if specimens.any?
              - specimens.each do |specimen|
                .row
                  .specimen_concept.col.s6.l6
                    %b
                      Specimen
                  .specimen_date.col.s6.l6
                    %b
                      Date
                .row
                  .specimen_concept.col.s6.l6
                    = specimen.specimen_concept.concept_name
                  .specimen_date.col.s6l6
                    = specimen.specimen_date.to_s(:date)
          .notes.col.s12.l3.center-align
            - notes = procedure_occurence.notes(username: current_user.username, except_notes: [@note])
            - if notes.any?
              - notes.each do |note|
                .row.note
                  .note_title.center-align.col.s6.l6
                    = note.note_title
                  .note_view.center-align.col.s6.l6
                    = link_to 'View', "#note_id_#{note.note_id}", class: 'waves-effect waves-light btn modal-trigger'
                    %div{id: "note_id_#{note.note_id}", class: 'modal' }
                      .modal-content.left-align
                        = render partial: 'note', locals: { note: note}
  #other_notes.row
  .row
    %h4.col.l12
      Other Notes
  .row
    .other_note_note_date.col.s12.l2
      %b
        Note Date
    .other_note_note_type.col.s12.l2
      %b
        Note Type
    .other_note_note_class.col.s12.l2
      %b
        Note Class
    .other_note_note_title.col.s12.l2
      %b
        Title
    .other_note_note_provider.col.s12.l2
      %b
        Provider
    .other_note_review.col.s12.l2

  - other_notes = @note.other_notes
  - if other_notes.any?
    - other_notes.each do |other_note|
      .row
        .other_note_note_date.col.s12.l2
          = other_note.note.note_date.to_s(:date)
        .other_note_note_type.col.s12.l2
          = @note.note_type.concept_name
        .other_note_note_class.col.s12.l2
          = @note.note_class.concept_name
        .other_note_note_title.col.s12.l2
          = @note.note_title
        .other_note_note_provider.col.s12.l2
          = @provider.provider_name if @provider.present?
        .other_note_review.col.s12.l2
          - other_note.abstractor_namespaces.each do |abstractor_namespace|
            = link_to "#{abstractor_namespace.name}:Review", edit_note_path(other_note.note.note_id, previous_note_id: other_note.note.note_id, index: 0, namespace_type: Abstractor::AbstractorNamespace.to_s, namespace_id: abstractor_namespace.id), { class: 'note_review_link' }
  #note_abstractions
    = render :partial => '/abstractor_abstractions/list', :locals => {:about => @note.note_stable_identifier, namespace_type: params[:namespace_type], namespace_id: params[:namespace_id] }
  .note_actions
    .actions
      - if @note.note_stable_identifier.submitted?
        = button_to 'Remove', Abstractor::UserInterface.abstractor_relative_path(update_wokflow_status_abstractor_abstractions_path()), data: { confirm: 'Are you sure?', controller: 'abstractor-abstraction', action: 'click->abstractor-abstraction#validateWorkflowStatus'}, method: :put, class: "abstractor_update_workflow_status_link_pend abstractor_update_workflow_status_link", remote: false, params: { about_type: @note.note_stable_identifier.class, about_id: @note.note_stable_identifier.id, abstraction_workflow_status: Abstractor::Enum::ABSTRACTION_WORKFLOW_STATUS_PENDING }, disabled: false, form_class: 'abstraction_workflow_status_form'
      - else
        = button_to 'Submit', Abstractor::UserInterface.abstractor_relative_path(update_wokflow_status_abstractor_abstractions_path()), data: { confirm: 'Are you sure?', controller: 'abstractor-abstraction', action: 'click->abstractor-abstraction#validateWorkflowStatus' }, method: :put, class: "abstractor_update_workflow_status_link_submit abstractor_update_workflow_status_link #{ @note.note_stable_identifier.fully_set? ? 'abstractor_update_workflow_status_link_enabled' : 'abstractor_update_workflow_status_link_disabled' }", remote: false, params: { about_type: @note.note_stable_identifier.class, about_id: @note.note_stable_identifier.id, abstraction_workflow_status: Abstractor::Enum::ABSTRACTION_WORKFLOW_STATUS_SUBMITTED }, disabled: !@note.note_stable_identifier.fully_set?, form_class: 'abstraction_workflow_status_form'
      |
      - if @note.note_stable_identifier.discarded?
        = link_to 'Undiscard', Abstractor::UserInterface.abstractor_relative_path(undiscard_abstractor_abstractions_path(about_type: @note.note_stable_identifier.class, about_id: @note.note_stable_identifier.id)), data: { confirm: 'Are you sure?'}, method: :put, class: 'abstractor_undiscard_case_link'
      - else
        = link_to 'Discard', Abstractor::UserInterface.abstractor_relative_path(discard_abstractor_abstractions_path(about_type: @note.note_stable_identifier.class, about_id: @note.note_stable_identifier.id)), data: { confirm: 'Are you sure?'}, method: :put, class: 'abstractor_discard_case_link'