config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :abstractor_abstraction_groups do
    member do
      put :update_wokflow_status
    end
  end

  resources :abstractor_abstractions do
    collection do
      put :update_all
      put :discard
      put :undiscard
      put :update_wokflow_status
    end
    member do
      put :clear
    end
    resources :abstractor_suggestions
  end

  resources :abstractor_abstraction_schemas, only: [:index, :show] do
    resources :abstractor_object_values
  end

  resources :abstractor_rules do
  end

  resources :abstractor_object_value_variants
  resources :notes do
    collection { get :next_note }
    collection { get :previous_note }
  end

  resources :note_stable_identifiers do
    member do
      post :abstractor_suggestions
    end
  end

  resources :providers, only: :index
  resources :provider_specialties, only: :index
  resources :users, only: :show

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/abstractor_abstractions_controller.rb
class AbstractorAbstractionsController < ApplicationController
  include Abstractor::Methods::Controllers::AbstractorAbstractionsController
end

app/views/abstractor_abstractions/_abstraction_history.html.haml
- if versions.any?
  %b
    History:
  = link_to '(Show)', '', class: 'show_hide_abstractor_history_link show_abstractor_history'
  .abstactor_history_content.hide
    - versions.each do |version|
      .version
        .version_date
          %i
            Date:
          = version.created_at.to_date.to_s(:date)
        .version_value
          %i
            Value:
          = version.reify.display_value
        .version_user
          %i
            User:
          = version.originator

app/views/abstractor_abstractions/_fields.html.haml
- abstractor_abstraction ||= @abstractor_abstraction
- read_only ||= @read_only
- unless abstractor_abstraction.blank?
  - abstractor_abstraction_schema   = abstractor_abstraction.abstractor_subject.abstractor_abstraction_schema
  - abstractor_suggestions          = abstractor_abstraction.abstractor_suggestions.not_deleted.order('suggested_value ASC, id DESC ')
  - rejected_suggestions            = abstractor_suggestions.not_deleted.where(accepted: false)
  - about = abstractor_abstraction.about
  .abstractor_abstraction_display
    .abstractor_abstraction_schema_name
      %h5
        = abstractor_abstraction_schema.display_name
    .abstractor_suggestions
      - if abstractor_suggestions.any?
        - abstractor_suggestions.each_with_index do |abstractor_suggestion, index|
          .abstractor_suggestion{ data: { controller: "abstractor-suggestion", target: 'abstractor-abstraction.suggestion abstractor-suggestion.suggestion' } }
            = form_for [abstractor_abstraction, abstractor_suggestion], url: Abstractor::UserInterface.abstractor_relative_path(abstractor_abstraction_abstractor_suggestion_path(abstractor_abstraction, abstractor_suggestion)), method: :put, remote: true, html: { class: 'edit_abstractor_suggestion' }, data: { action: 'ajax:complete->abstractor-abstraction#render' } do |f|
              = render 'shared/error_messages', object: f.object
              .abstractor_suggestion_status
                - id = "abstractor_suggestion_accepted_#{abstractor_suggestion.id}"
                %label
                  = f.check_box :accepted, id: id, class: "abstractor_suggestion_status_selection #{display}", disabled: read_only, data: { action: 'change->abstractor-suggestion#determine' }
                  %span
                    = abstractor_suggestion.display_value
                .abstractor_suggestion_values
                  - if abstractor_suggestion.abstractor_suggestion_sources.any? && abstractor_suggestion.display_value != Abstractor::Enum::ABSTRACTION_OTHER_VALUE_TYPE_NOT_APPLICABLE
                    - abstractor_suggestion.normalize_abstractor_suggestion_sentences.each do |source|
                      - abstractor_text = Abstractor::AbstractorAbstractionSource.abstractor_text(source)
                      - if abstractor_text && source[:sentences].any?
                        %span{ class: 'abstractor_abstraction_source_tooltip_img', rel:"#abstraction_text_#{abstractor_suggestion.id}_#{Abstractor::UserInterface.generate_source_id(source)}", title: "#{source[:source_type].to_s.underscore.humanize.titleize}: #{source[:source_method].to_s.humanize}", data: { target: 'abstractor-suggestion.tooltip', action: 'click->abstractor-suggestion#handleHighlight' }}
                          %i{ id: "abstraction_text_link_#{Abstractor::UserInterface.generate_source_id(source)}", class: "abstraction_text_link_match right-align" }
                        %div{ id: "abstraction_text_#{abstractor_suggestion.id}_#{Abstractor::UserInterface.generate_source_id(source)}", class: 'abstractor_abstraction_source_tooltip hide' }
                          .abstractor_source_tab
                            = Abstractor::UserInterface.generate_source_id(source)
                          .section_name
                            = source[:section_name]
                          - source[:sentences].each do |sentence|
                            .sentence
                              .sentence_match_value
                                = ERB::Util.html_escape(sentence[:sentence])
                                .hashed_sentence
                                  = hashed_sentence = sentence[:sentence].hash
                              - sentence[:match_values].each do |match_value|
                                .match_value
                                  = ERB::Util.html_escape(match_value.strip)
                - abstractor_suggestion.abstractor_suggestion_sources.custom.each do |abstractor_suggestion_source|
                  .custom_explanation
                    %label
                      Explanation:
                    .explanation_text
                      = abstractor_suggestion_source.custom_explanation
      - else
        - abstractor_abstraction.abstractor_subject.abstractor_abstraction_sources.select { |s| s.abstractor_abstraction_source_type.name == 'nlp suggestion' }.each do |abstractor_abstraction_source|
          - abstractor_abstraction_source.normalize_from_method_to_sources(abstractor_abstraction.about).each do |source|
            - abstractor_text = Abstractor::AbstractorAbstractionSource.abstractor_text(source)
            - dom_id = "#{abstractor_abstraction_source.id}_#{source[:source_type]}_#{source[:source_id]}_#{source[:source_method]}#{'_'+ source[:section_name].parameterize.underscore if source[:section_name]}"
            %span{ class: 'abstractor_abstraction_source_tooltip_img', rel: "#abstraction_text_#{dom_id}", title: "#{source[:source_type].to_s} #{source[:source_method]} #{source[:section_name]}"}
              %i{ id: "abstraction_text_link_#{dom_id}" }
            %div{ id: "abstraction_text_#{dom_id}", class: 'tooltip'}
              = format_text(abstractor_text)
      .abstractor_abstraction_value
        .links.right-align
          - unless read_only
            = link_to 'Edit', Abstractor::UserInterface.abstractor_relative_path(edit_abstractor_abstraction_path(abstractor_abstraction)), class: 'edit_link', data: { action: 'click->abstractor-abstraction#edit' }
            |
            = link_to 'Clear', Abstractor::UserInterface.abstractor_relative_path(clear_abstractor_abstraction_path(abstractor_abstraction)), class: 'clear_link waves-effect waves-light btn red', data: { action: 'click->abstractor-abstraction#clear' }
        - if show_abstractor_history?
          - versions = abstractor_abstraction.versions.sort{|a,b| b.created_at <=> a.created_at}.reject{|v| v.reify.blank? || v.reify.display_value =~ /not set/i}
          .abstractor_history
            = render partial: 'abstractor_abstractions/abstraction_history', locals: { versions: versions }

app/views/abstractor_abstractions/_grouped_abstractions_list.html.haml
- namespace_type ||= @namespace_type
- namespace_id ||= @namespace_id

.abstractor_abstractions_grouped
  - abstractor_subject_groups = about.class.abstractor_subject_groups(namespace_type: namespace_type, namespace_id: namespace_id)
  - abstractor_subject_groups.each do |abstractor_subject_group|
    .abstractor_subject_groups_container{ data: { controller: 'abstractor-abstraction-groups' } }
      %h4
        =abstractor_subject_group.name
      - if abstractor_subject_group.cardinality
        = hidden_field_tag :abstractor_subject_group_cardinality, abstractor_subject_group.cardinality, id: "abstractor_subject_group_cardinality_#{abstractor_subject_group.id}"
      %fieldset
        - if show_abstractor_headers?
          .abstractor_abstractions_header
            .abstractor_abstraction_schema_name
              %b Name
            .abstractor_suggestions
              .abstractor_suggestion_values
                %b Suggestions
          .clear
        .abstractor_abstractions_body.abstractor_subject_groups
          - abstractor_abstraction_groups = about.abstractor_abstraction_groups_by_namespace(namespace_type: namespace_type, namespace_id: namespace_id, abstractor_subject_group_id: abstractor_subject_group.id)
          - abstractor_abstraction_groups.each do |abstractor_abstraction_group|
            = render partial: 'abstractor_abstraction_groups/form', locals: {abstractor_abstraction_group: abstractor_abstraction_group, namespace_type: namespace_type, namespace_id: namespace_id}
        - unless abstractor_subject_group.cardinality == 1 || about.discarded? || about.submitted?
          = link_to "Add #{abstractor_subject_group.name}", Abstractor::UserInterface.abstractor_relative_path(abstractor_abstraction_groups_path(about_id: about.id, about_type: about.class.name, abstractor_subject_group_id: abstractor_subject_group.id, namespace_type: namespace_type, namespace_id: namespace_id)), method: :post, class: 'waves-effect waves-light btn abstractor_group_add_link', remote: true, style: "#{'display: none;' if about.abstractor_subject_group_complete?(abstractor_subject_group.id, {namespace_type: namespace_type, namespace_id: namespace_id})}", data: { confirm: 'Are you sure?', action: 'ajax:complete->abstractor-abstraction-groups#add' }

app/views/abstractor_abstractions/_list.html.haml
- about ||= @about
- namespace_type ||= @namespace_type
- namespace_id ||= @namespace_id


.wrapper
  .abstractor_footer.sticky
    .abstractor_sources_tabs
      - about.sources.each_with_index do |source, i|
        .abstractor_source_tab{ id: "#{Abstractor::UserInterface.generate_source_id(source)}" }
          = radio_button_tag "abstractor_source_tab", i,  name: "abstractor_source_tabs", checked: nil
          = label_tag "abstractor_source_tab_#{i}", "#{source[:source_method].to_s.humanize}", for: "abstractor_source_tab_#{i}"
          .abstractor_source_tab_content
            - abstractor_text = Abstractor::AbstractorAbstractionSource.abstractor_text(source)
            - if abstractor_text
              - unless source[:abstractor_suggestion_sources].blank?
                - source[:abstractor_suggestion_sources].each do |abstractor_suggestion_source|
                  - unless abstractor_suggestion_source[:sentence_match_value].blank?
                    - hashed_sentence = abstractor_suggestion_source[:sentence_match_value].hash
                    - abstractor_text = Abstractor::UserInterface.highlight(ERB::Util.html_escape(abstractor_text), ERB::Util.html_escape(abstractor_suggestion_source[:sentence_match_value].strip), highlighter: %{<strong class="abstractor_highlight #{hashed_sentence.to_s}">\\1</strong>})
              = format_text(ERB::Util.html_escape(abstractor_text))
  .abstractor_abstractions
    - if show_abstractor_all_links?
      .abstractor_all_links
        = link_to 'Not applicable all', Abstractor::UserInterface.abstractor_relative_path(update_all_abstractor_abstractions_path(about_type: about.class, about_id: about.id, abstractor_abstraction_value: 'not applicable', namespace_type: namespace_type, namespace_id: namespace_id)), data: { confirm: 'Are you sure?'}, method: :put, class: 'abstractor_not_applicable_all_link waves-effect waves-light btn'
        = link_to 'Unknown all', Abstractor::UserInterface.abstractor_relative_path(update_all_abstractor_abstractions_path(about_type: about.class, about_id: about.id, abstractor_abstraction_value: 'unknown', namespace_type: namespace_type, namespace_id: namespace_id)), data: { confirm: 'Are you sure?'}, method: :put,  class: 'abstractor_unknown_all_link waves-effect waves-light btn'
    - if flash[:abstractor_errors]
      %div{ :id => "abstractor_error", :class => "message"}
        - flash[:abstractor_errors].each do |error|
          = error
    = render partial: 'abstractor_abstractions/grouped_abstractions_list',   locals: { about: about, namespace_type: namespace_type, namespace_id: namespace_id}
    = render partial: 'abstractor_abstractions/ungrouped_abstractions_list', locals: { about: about, namespace_type: namespace_type, namespace_id: namespace_id}

app/views/abstractor_abstractions/_ungrouped_abstractions_list.html.haml
.abstractor_abstractions_ungrouped
  - ungrouped_subjects = about.class.abstractor_subjects(grouped: false, namespace_type: namespace_type, namespace_id: namespace_id).order('abstractor_subjects.id')
  - if ungrouped_subjects.any?
    %fieldset
      - if show_abstractor_headers?
        .abstractor_abstractions_header
          .abstractor_abstraction_schema_name
            %b Name
          .abstractor_suggestions
            .abstractor_suggestion_values
              %b Suggestions
      .abstractor_abstractions_body
        - ungrouped_subjects.each_with_index do |ungrouped_subject, index|
          - abstractor_abstractions = ungrouped_subject.abstractor_abstractions.not_deleted.where(:about_id => about.id)
          - abstractor_abstractions.each do |abstractor_abstraction|
            %div{ class: "abstractor_abstraction #{Abstractor::Utility.dehumanize(abstractor_abstraction.abstractor_subject.abstractor_abstraction_schema.predicate)} #{'abstractor_bottom_border' if index < ungrouped_subjects.length - 1}", data: { controller: 'abstractor-abstraction' } }
              = render :partial => 'abstractor_abstractions/fields', :locals => {:abstractor_abstraction => abstractor_abstraction}

app/views/abstractor_abstractions/edit.html.haml
- abstractor_abstraction ||= @abstractor_abstraction
- abstraction_schema = abstractor_abstraction.abstractor_subject.abstractor_abstraction_schema

.abstractor_abstraction_edit
  = form_for abstractor_abstraction, url: Abstractor::UserInterface.abstractor_relative_path(abstractor_abstraction_path(abstractor_abstraction)), method: :put, :remote => true, data: { action: 'ajax:success->abstractor-abstraction#save ajax:error->abstractor-abstraction#saveError' } do |f|
    .abstractor_abstraction_schema_name
      %h5
        = abstraction_schema.display_name
    .abstraction_edit_abstraction_value
      - case abstraction_schema.abstractor_object_type.value
      - when 'date'
        = f.text_field :value, class: 'abstractor_datepicker'
        - if validation_errors?(abstractor_abstraction, :value)
          %span.helper-text{ 'data-error' => "#{format_validation_errors(abstractor_abstraction, :value)}"}
      - when 'text'
        .input-field
          = f.text_area :value, class: 'materialize-textarea'
          - if validation_errors?(abstractor_abstraction, :value)
            %span.helper-text{ 'data-error' => "#{format_validation_errors(abstractor_abstraction, :value)}"}
      - when 'string'
        = f.text_field :value
        - if validation_errors?(abstractor_abstraction, :value)
          %span.helper-text{ 'data-error' => "#{format_validation_errors(abstractor_abstraction, :value)}"}
      - when 'number'
        = f.number_field :value, step: :any
        - if validation_errors?(abstractor_abstraction, :value)
          %span.helper-text{ 'data-error' => "#{format_validation_errors(abstractor_abstraction, :value)}"}
      - when 'radio button list'
        - values = abstraction_schema.abstractor_object_values.not_deleted.order('abstractor_abstraction_schema_object_values.display_order, abstractor_object_values.value')
        -  values.each do |value|
          %label
            = f.radio_button :value, value.value, required: 'required'
            %span
              = value.value
        = f.radio_button :value, '', {:style => 'display:none;' }
        &nbsp;
      - when 'list'
        - values = abstraction_schema.abstractor_object_values.not_deleted.order('abstractor_abstraction_schema_object_values.display_order, abstractor_object_values.value')
        = f.select :value, options_for_select(values.map{|s| [s.value, s.value]}, selected: f.object.value), { include_blank: true }
        - if validation_errors?(abstractor_abstraction, :value)
          %span.helper-text{ 'data-error' => "#{format_validation_errors(abstractor_abstraction, :value)}"}
      - when 'dynamic list'
        - values = abstractor_abstraction.about.send(abstractor_abstraction.abstractor_subject.dynamic_list_method).sort_by { |l| l[:value] }
        = f.select :value, values.map{|s| [s[:value], s[:id]]}, {:include_blank => true}, :class => "combobox"
      - when 'boolean'
        - ['true', 'false'].each do |value|
          = f.radio_button :value, value
          = f.label :value, value
        = f.radio_button :value, '', {:style => 'display:none;'}
        &nbsp;
      - else
        = f.text_field :value
      - if show_abstractor_edit_other_values?
        %br
        %label
          = f.check_box :not_applicable
          %span
            Not Applicable
        &nbsp;
        %label
          = f.check_box :unknown
          %span
            Unknown
    .abstraction_edit_abstraction_actions
      = f.submit 'Save', class: 'waves-effect waves-light btn'
      = link_to 'Cancel', abstractor_abstraction_path(abstractor_abstraction), :remote => true, data: { action: 'ajax:complete->abstractor-abstraction#render' }
    .clear
    .indirect_sources
      - abstraction_sources = abstractor_abstraction.abstractor_subject.abstractor_abstraction_sources.select { |s| s.abstractor_abstraction_source_type.name == 'indirect' }
      = f.fields_for :abstractor_indirect_sources, f.object.abstractor_indirect_sources do |abstractor_indirect_source_form|
        .indirect_source
          - abstraction_source = abstraction_sources.select { |abstraction_source| abstraction_source.id == abstractor_indirect_source_form.object.abstractor_abstraction_source_id }.first
          - source_setup = abstractor_abstraction.about.send(abstraction_source.from_method)
          - sources = source_setup[:sources].all
          %label
            Indirect Source:
            = source_setup[:source_type].tableize.humanize
          %br
          = abstractor_indirect_source_form.select :source_id, sources.map{ |s| [s.send(source_setup[:source_name_method]), s.id] }, { :include_blank => 'None' }, :size => "#{sources.size + 1}", class: 'indirect_source_list', rel: "#{source_setup[:source_type]}"
          - sources.each do |source|
            - hidden = abstractor_indirect_source_form.object.source_id == source.id ? '' : 'hidden'
            %div{ class: "indirect_source_text #{hidden} #{source_setup[:source_type]}_#{source.id}"}
              = format_text(ERB::Util.html_escape(source.send(source_setup[:source_method])))

app/views/abstractor_abstractions/show.html.haml
= render :partial => 'abstractor_abstractions/fields'